ALTER VIEW dbo.VW_IMIS_rev_Assess
AS
(select 

assess_vw.[Account],
 [Amended],
 [Inactive],
[Amended From],
[Assess Mail],
[Assess Year],
[Authorized Person Email],
[Authorized Person First Name],
[Authorized Person Last Name],
[Bill Cycle],
[Billing Entity],
[Completed],
[Completed By Contact],
[Completed Date],
[Customer Calculation],
[Exempt Status],
[Exempt Notes],
[Filed By User],
[Filed Date],
[Filed Online],
[Fiscal End Date],
FORMAT(CONVERT(INT,[Fiscal End Month]), '00') [Fiscal End Month],
[Fiscal Start Date],
[Fiscal Start Month],
[Gross Reciept],
[IMIS Assessment Calculation],
[IMIS Interest],
[IMIS IsPaid],
[IMIS Num of Months],
[Pass Thru Total],
[IMIS Post Mark Date],
[Primary Assessment Rate], 
[Primary Gross Revenue],
[Primary Percent Tourism],
[Payment Overage],
[IMIS Payment Plan],
[IMIS Ready to Post],
[Secondary Assessment Rate],
[Secondary Gross Revenue],
[Secondary Percent Tourism],
[Segment Category],
[Segment Code],
[Segment Max],
[Signature],
[Supersede By],
[Superseded],
[Total Admin Fees],
[Use Seg Max],
[IMIS Under 1M Comment],
[Voluntary Assessment],
[IMIS Voluntary Max],
[7% Decrease in Revenue],
[7 Point Decrease in TNT],
[Audit Year],
[Low TNT],
[Reason for Audit],
[Repeated Revenue],
[Rounded Revenue],
[Secondary TNT],
[Zero TNT],
[IMIS Low TNT Cleared],
[IMIS Low TNT Drop Code],
[IMIS DecreaseRevenue Cleared] ,
[IMIS DecreaseRevenue Drop Code],
[IMIS DecreaseTNT Cleared],
[IMIS DecreaseTNT Drop Code],
[IMIS NoTNT Cleared],
[IMIS NoTNT Drop Code],
[IMIS RoundedRevenue Cleared],
[IMIS RoundedRevenue Drop Code],
[IMIS RepeatRevenue Cleared],
[IMIS RepeatRevenue Drop Code],
[Audit],
[IMIS Secondary TNT Cleared],
[IMIS Secondary TNT Drop Code],
[Balance Due],
[Balance Due Cleared],
[Audit Note],
[IMIS Miscalculation],
[IMIS Miscalculation Cleared],
[IMIS NAD Property],
[IMIS Filing Notice Number],
[IMIS Balance Notice Number],
[IMIS Audit Notice Number],
[IMIS Missed Projection Reason],
[IMIS Below1Mil],
[IMIS Below1mil_Cleared] ,
assess_audit_vw.[IMIS Writeoff Amount],
assess_vw.[External Id] as [External ID]
from  BOOMI_DEV.dbo.VW_IMIS_Assess assess_vw 
LEFT JOIN BOOMI_DEV.dbo.VW_IMIS_Assess_Audit assess_audit_vw on assess_vw.Account = assess_audit_vw.Account and assess_vw.[Assess Year] = assess_audit_vw.[Audit Year])