ALTER VIEW dbo.VW_IMIS_rev_Assess_Car
AS
(select 

assess_car_vw.[Account],
[Assess Year],
[Authorized Person Email],
[Authorized Person First Name],
[Authorized Person Last Name],
[Billing Entity],
[Completed Date],
[Filed By User],
[Filed Date],
[Filed Online],
[Fiscal End Date],
[Fiscal End Month],
[Fiscal Start Date],
[Fiscal Start Month],
[IMIS Assessment Calculation],
[Period],
[Primary Assessment Rate],
[Primary Gross Revenue],
[Segment Code],
[Segment Category],
[Signature],
[7% Decrease in Revenue],
[7 Point Decrease in TNT],
[Audit Year],
[Low TNT],
[Reason for Audit],
[Repeated Revenue],
[Rounded Revenue],
[Secondary TNT],
[Zero TNT],
[IMIS Low TNT Cleared],
[IMIS Low TNT Drop Code],
[IMIS DecreaseRevenue Cleared] ,
[IMIS DecreaseRevenue Drop Code],
[IMIS DecreaseTNT Cleared],
[IMIS DecreaseTNT Drop Code],
[IMIS NoTNT Cleared],
[IMIS NoTNT Drop Code],
[IMIS RoundedRevenue Cleared],
[IMIS RoundedRevenue Drop Code],
[IMIS RepeatRevenue Cleared],
[IMIS RepeatRevenue Drop Code],
[Audit],
[IMIS Secondary TNT Cleared],
[IMIS Secondary TNT Drop Code],
[Balance Due],
[Balance Due Cleared],
[Audit Note],
[IMIS Miscalculation],
[IMIS Miscalculation Cleared],
[IMIS NAD Property],
[IMIS Filing Notice Number],
[IMIS Balance Notice Number],
[IMIS Audit Notice Number],
[IMIS Missed Projection Reason],
[IMIS Below1Mil],
[IMIS Below1mil_Cleared] ,
assess_audit_vw.[IMIS Writeoff Amount],
assess_car_vw.[External Id] as [External ID]
from  BOOMI_DEV.dbo.VW_IMIS_Assess_Car assess_car_vw 
LEFT JOIN BOOMI_DEV.dbo.VW_IMIS_Assess_Audit assess_audit_vw on assess_car_vw.Account = assess_audit_vw.Account and assess_car_vw.[Assess Year] = assess_audit_vw.[Audit Year])